### ISSUE TITLE
Documentation Update

### ISSUE THREAD

**Issue by shubham7saxena** [Arafatk/glot#2]
The library should have a proper readme apart from the documentation. Would love to take over the task if you guys are not already over it.

**Comment by arafatkatze** [comment]
@shubham7saxena Updated the godoc reference.     
I still think that the documentation is slightly incomplete and probably not self explanatory.       
You are more than welcome to contribute.          
Thanks a lot.

**Comment by arafatkatze** [comment]
@shubham7saxena I'm sorry,  I probably misread your post.    
Yes the README is very concise now.    
Please go ahead and send a pull request.   

Thanks

**Comment by shubham7saxena** [comment]
@Arafatk sure. will start with it.

**Comment by shubham7saxena** [comment]
@Arafatk - do you guys happen to have a slack channel for community and open source discussion. If yes, please share the link with me. If not, let's have one 😄

**Comment by arafatkatze** [comment]
@shubham7saxena How about making a Gitter channel?

**Comment by shubham7saxena** [comment]
sure, any place where people can have meaningful discussions without any hassles is good to start with. 😄 . just create one and let me know. will be happy to put it in the upcoming updated readme.

**Comment by arafatkatze** [comment]
@shubham7saxena Done

**Comment by arafatkatze** [comment]
@shubham7saxena I am okay with the new README.      
Looks better.
