### ISSUE TITLE
Qt-based gnuplot process is still alive even after closing UI

### ISSUE THREAD

**Issue by helloworldpark** [Arafatk/glot#24]
Steps
1. Run a gnuplot
2. Make it open for a few seconds
3. Close the gnuplot's window
4. Check the process monitor. _gnuplot_ and _gnuplot_qt_ is still alive

Environment
 - go 1.13
 - macOS Catalina 10.15.3
 - gnuplot 5.2 patchlevel 8
 - installed gnuplot by homebrew 2.2.10

**Comment by helloworldpark** [comment]
Tested using gnuplot installed in my computer, and figured out it seems to be not a bug but implementation.
Testing the same way, the processes are both alive. Closing the issue.

**Comment by arafatkatze** [comment]
@helloworldpark Good to know you figured it out. 

Thanks for raising the issue.
