### ISSUE TITLE
[enhancement] using go libraries for test coverage report generation

### ISSUE THREAD

**Issue by shubham7saxena** [Arafatk/glot#5]
hey @Arafatk , just saw the travis build and the test_coverage.sh for test coverage report generation. May I know the thought process behind using that. there does exist tools such as [gocov] (https://github.com/axw/gocov). Do check it out. Also, do you mind sharing the test_coverage.sh. I will be happy to run down a comparsion between the two and raise a pull request in case some other tool looks good.

**Comment by arafatkatze** [comment]
@shubham7saxena I added the file.     
And I am checked out gocov.    
It's pretty cool.   
You are welcome to run the tests.

**Comment by shubham7saxena** [comment]
@Arafatk I will add gocov and gocyclo for cyclomatic complexity. You can assign the issue to me. will try to finish it by the weekend. Cheers 😄

**Comment by arafatkatze** [comment]
@shubham7saxena That's really nice.    
Thanks a lot.

**Comment by arafatkatze** [comment]
Pull Request #8       
Solves this
